version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tada-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  web:
    build: .
    container_name: tada_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      .env
    command: >
      sh -c "echo 'Waiting for database to be ready...' &&
             sleep 10 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - tada-network

volumes:
  postgres_data:

networks:
  tada-network:
    driver: bridge