# Generated by Django 5.2.4 on 2025-09-27 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
